// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1uey7PACl_qCziGLuX27kmguHUaeUZPQ',
    appId: '1:194524818384:web:d3c5a304c9a2c77333a7d5',
    messagingSenderId: '194524818384',
    projectId: 'iem-attendance-app',
    authDomain: 'iem-attendance-app.firebaseapp.com',
    storageBucket: 'iem-attendance-app.firebasestorage.app',
    measurementId: 'G-5S1EB93VZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE55CtnyvHRytSI4M15IRtSNa7M3-gfXc',
    appId: '1:194524818384:android:9627393bde91652233a7d5',
    messagingSenderId: '194524818384',
    projectId: 'iem-attendance-app',
    storageBucket: 'iem-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByjZ59-z1LqGgbKXlnK-JWFijjC_MI5HQ',
    appId: '1:194524818384:ios:8d7b752415d7e70433a7d5',
    messagingSenderId: '194524818384',
    projectId: 'iem-attendance-app',
    storageBucket: 'iem-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.iemAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByjZ59-z1LqGgbKXlnK-JWFijjC_MI5HQ',
    appId: '1:194524818384:ios:8d7b752415d7e70433a7d5',
    messagingSenderId: '194524818384',
    projectId: 'iem-attendance-app',
    storageBucket: 'iem-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.iemAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1uey7PACl_qCziGLuX27kmguHUaeUZPQ',
    appId: '1:194524818384:web:646fef79e21324d833a7d5',
    messagingSenderId: '194524818384',
    projectId: 'iem-attendance-app',
    authDomain: 'iem-attendance-app.firebaseapp.com',
    storageBucket: 'iem-attendance-app.firebasestorage.app',
    measurementId: 'G-2B6BV6FCRG',
  );
}
